### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "<local6>" is null

### ISSUE THREAD

**Issue by servicomcr** [GC-spigot/AdvancedItems#69]
[22:41:57 WARN]: java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "<local6>" is null
[22:41:57 WARN]:        at AdvancedItems-1.10.5.jar//net.advancedplugins.items.handlers.ItemsAbilities.getRawAbilities(ItemsAbilities.java:29)
[22:41:57 WARN]:        at AdvancedItems-1.10.5.jar//net.advancedplugins.items.impl.commons.effects.actions.ActionExecutionBuilder.build(ActionExecutionBuilder.java:91)
[22:41:57 WARN]:        at AdvancedItems-1.10.5.jar//net.advancedplugins.items.impl.commons.effects.mechanics.triggers.internal.RepeatingTrigger.activate(RepeatingTrigger.java:69)
[22:41:57 WARN]:        at AdvancedItems-1.10.5.jar//net.advancedplugins.items.impl.commons.effects.mechanics.triggers.internal.ArmorWearTrigger.runCheck(ArmorWearTrigger.java:225)
[22:41:57 WARN]:        at AdvancedItems-1.10.5.jar//net.advancedplugins.items.impl.commons.effects.mechanics.triggers.internal.ArmorWearTrigger.updateWornArmor(ArmorWearTrigger.java:198)
[22:41:57 WARN]:        at AdvancedItems-1.10.5.jar//net.advancedplugins.items.impl.commons.effects.mechanics.triggers.internal.ArmorWearTrigger.lambda$onPlayerJoin$1(ArmorWearTrigger.java:88)
[22:41:57 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[22:41:57 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[22:41:57 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724)
[22:41:57 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473)
[22:41:57 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596)
[22:41:57 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302)
[22:41:57 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[22:41:57 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

[22:42:39 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:40 ERROR]: Could not pass event ProjectileHitEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:41 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:42 ERROR]: Could not pass event ProjectileHitEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:43 INFO]: MrGREGORY90 issued server command: /home casa
[22:42:44 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:45 ERROR]: Could not pass event ProjectileHitEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:46 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:47 ERROR]: Could not pass event ProjectileHitEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:47 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:49 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:50 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:50 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:51 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:51 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:52 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:52 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:53 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:53 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:54 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:54 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:55 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:55 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:56 ERROR]: Could not pass event EntityDamageEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:57 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:57 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:57 ERROR]: Could not pass event EntityDamageEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:58 ERROR]: Could not pass event EntityDamageEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:58 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:42:59 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:00 ERROR]: Could not pass event EntityDamageEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:00 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:00 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:00 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:01 ERROR]: Could not pass event EntityDamageEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:01 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:01 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:01 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:01 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:02 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:02 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:02 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:04 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:04 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:05 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:06 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:06 ERROR]: Could not pass event EntityDeathEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:08 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:10 ERROR]: Could not pass event PlayerItemConsumeEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:12 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:15 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:17 INFO]: [Not Secure] survival >> ✦✧ Dark Pass ✧✦  >> Rochitocr >> Buenas
[22:43:23 INFO]: [Not Secure] survival >>   [ 🍋  [   >> .Limon0512 >> buenas
[22:43:26 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:26 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:28 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:29 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:29 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:29 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:29 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:29 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:30 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:30 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:30 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:30 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:30 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:30 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:31 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:31 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:31 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:31 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:31 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:32 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:32 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:32 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:32 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:32 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:32 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:33 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:33 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:33 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:33 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:33 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:34 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:34 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:34 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:34 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:34 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:35 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:35 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:35 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:35 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:35 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:35 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:35 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:35 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:36 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:36 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:36 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:36 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:36 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:36 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:37 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:37 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:37 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:37 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:37 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:38 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:38 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:38 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:38 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:38 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:39 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:39 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:39 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:39 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:39 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:40 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:41 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:42 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:42 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:43 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:43 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:43 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:46 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:48 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:43:53 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:00 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:00 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:00 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:01 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:01 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:01 WARN]: .Limon0512 moved too quickly! 0.0,24.0,0.0
[22:44:02 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:03 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:03 WARN]: .Limon0512 moved too quickly! 0.0,47.0,0.0
[22:44:03 WARN]: .Limon0512 moved too quickly! 0.0,47.0,0.0
[22:44:03 WARN]: .Limon0512 moved too quickly! 0.0,47.0,0.0
[22:44:11 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:13 ERROR]: Could not pass event EntityDamageEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:18 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:18 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:18 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:19 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:19 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:19 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:20 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:20 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:20 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:21 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:21 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:22 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:23 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:23 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:23 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:26 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:29 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:36 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:36 WARN]: .Limon0512 moved too quickly! 0.0,47.0,0.0
[22:44:36 WARN]: .Limon0512 moved too quickly! 0.0,47.0,0.0
[22:44:36 WARN]: .Limon0512 moved too quickly! 0.0,47.0,0.0
[22:44:39 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:40 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:54 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:54 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:55 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:55 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:56 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:56 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:57 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:57 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:57 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:57 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:44:58 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:00 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:00 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:01 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:02 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:02 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:03 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:03 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:04 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:06 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:07 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:07 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:08 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:08 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:09 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:14 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:15 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:16 ERROR]: Could not pass event ProjectileHitEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:16 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:16 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:17 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:18 ERROR]: Could not pass event ProjectileHitEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:18 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:20 ERROR]: Could not pass event ProjectileHitEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:21 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:23 ERROR]: Could not pass event ProjectileHitEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null
[22:45:23 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.5
java.lang.NullPointerException: null

**Comment by servicomcr** [comment]
java.lang.NullPointerException: null
[00:21:08 ERROR]: Could not pass event BlockBreakEvent to AdvancedItems v1.10.6
java.lang.NullPointerException: null
[00:21:12 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.6
java.lang.NullPointerException: null
[00:21:13 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.6
java.lang.NullPointerException: null
[00:21:15 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.6
java.lang.NullPointerException: null
[00:21:18 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.6
java.lang.NullPointerException: null
[00:21:22 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.6
java.lang.NullPointerException: null
[00:21:23 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.6
java.lang.NullPointerException: null
[00:21:26 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.6
java.lang.NullPointerException: null
[00:21:31 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.6
java.lang.NullPointerException: null
[00:21:36 ERROR]: Could not pass event PlayerInteractEvent to AdvancedItems v1.10.6
java.lang.NullPointerException: null
[00:21:54 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.6
java.lang.NullPointerException: null
[00:21:55 ERROR]: Could not pass event PlayerJumpEvent to AdvancedItems v1.10.6

**Comment by servicomcr** [comment]
[05:27:07 INFO]: This server is running Paper version 1.21.1-131-ver/1.21.1@84281ce (2024-10-31T17:43:44Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-130-4d2672e (MC: 1.21.1)

**Comment by SirJben** [comment]
Hi @servicomcr how to reproduce this error?
